services:
  db:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-noterag}
      - POSTGRES_USER=${POSTGRES_USER:-noterag}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-noterag}
      - PGVECTOR_EMBEDDING_DIMENSIONS=${PGVECTOR_EMBEDDING_DIMENSIONS:-1024}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./temp/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-noterag}"]
      interval: 5s
      timeout: 5s
      retries: 5
